#!/bin/bash

# Settings and options
o_get=no
o_install=no
o_verbose=default
o_help=no
o_show=no
o_pkg=''

root="$HOME/pak-root"

temp_dir="/tmp/pak/download-$RANDOM-$RANDOM-$RANDOM-$RANDOM/"

paklist_dir="$root/paklist.d"


help_exit_status=0

version="1.2 костыль edition"

# String data
version_string="PAK v $version"
usage_string="Usage: $0 [-g|-i|-v|-q|-S|-h|-V|-u|-U|-r|-m] [--get|--install|--verbose|--silent|--show|--help|--version|--usage|--uninstall|--update|--root|--mirror] FILE_URL_OR_PACKAGE_NAME"
help_string="
    -g|--get        Download package
    -i|--install    Only install package, don't download
    -v|--verbose    Be verbose
    -q|--silent     Output nothing, only return an exit status
    -S|--show       Only show package information, don't install
    -h|--help       Show this help
       --usage      Show a brief usage information
    -V|--version    Show version information
    -u|--uninstall  Uninstall package
    -U|--update     Update package list
    -r|--root       Print pak_root value
    -m|--mirror     Get package from mirror"

# Functions
die()
{
    rm -rf "$temp_dir"
    case $o_verbose in
        silent)
            false
            ;;
        *)
            echo -e "\e[31mFatal error: $1\e[0m" >&2
    esac
    exit 1
}

output()
{
    case $o_verbose in
        silent)
            true
            ;;
        *)
            if ([ x$2 == x-v ] && [ $o_verbose == verbose ]) || [ x$2 != x-v ]; then
                echo -e "$1"
            fi
            ;;
    esac
}

ask()
{
    case $o_verbose in
        silent)
            return 0
            ;;
        *)
            output "$1"
            read ans
            case $ans in
                y|yes|Y|Yes|YES)
                    return 0
                    ;;
                *)
                    return 1
                    ;;
            esac
            ;;
    esac
}

show_help()
{
    case $o_help in
        usage)
            echo "$usage_string"
            ;;
        help)
            echo "$usage_string"
            echo "$help_string"
            ;;
        version)
            echo "$version_string"
            ;;
        root)
            echo "$root"
            ;;
        *)
            return 0
            ;;
    esac
    return $help_exit_status
}

# Parse args
while [ x$1 != x ]; do
    case $1 in
        -g|--get)
            o_get=yes
            o_install=yes
            o_help=no
            ;;
        -i|--install)
            o_install=yes
            o_get=no
            o_help=no
            ;;
        -v|--verbose)
            o_verbose=verbose
            ;;
        -q|--silent)
            o_verbose=silent
            ;;
        -S|--show)
            o_show=yes
            o_install=no
            o_help=no
            ;;
        -h|--help)
            o_install=no
            o_get=no
            o_help=help
            ;;
        -r|--root)
            o_install=no
            o_get=no
            o_help=root
            ;;
        --usage)
            o_install=no
            o_get=no
            o_help=usage
            ;;
        -V|--version)
            o_help=version
            ;;
        -u|--uninstall)
            o_install=uninstall
            o_help=no
            ;;
        -U|--update)
            o_install=update
            o_get=no
            o_help=no
            ;;
        -m|--mirror)
            o_install=yes
            o_get=mirror
            o_help=no
            ;;
        -*)
            o_help=usage
            help_exit_status=1
            ;;
        *)
            o_pkg="$1"
            ;;
    esac
    shift
done


#echo "Args:
#  -g=$o_get
#  -i=$o_install
#  -v=$o_verbose
#  -h=$o_help
#  -S=$o_show
#"
show_help || exit 1

pak_fname="$o_pkg"

mkdir -p "$root"

case $o_get in
    yes)
        pak_url="$o_pkg"
        mkdir -p "$temp_dir" || die 'Unable to create temporary directory'
        wget -O "$temp_dir/package.pak" "$pak_url" || die 'Unable to get the package'
        pak_fname="$temp_dir/package.pak"
        ;;
    mirror)
        pak_url=""
        for i in `ls "$paklist_dir"`; do
            s=`cat "$paklist_dir/$i" | egrep "^$o_pkg "`
            #echo "s = [$s]"
            if [ "x$s" != x ]; then
                pak_url=`echo "$s" | awk '{print $2}'`
                #echo "pu = [$pak_url]"
                if [ "x$pak_url" == x ]; then
                    continue
                else
                    break
                fi
            fi
        done
        #echo "[x$pak_url]"
        if [ "x$pak_url" == x ]; then
            die "Package \`$o_pkg' not found"
        fi
        mkdir -p "$temp_dir" || die 'Unable to create temporary directory'
        wget -O "$temp_dir/package.pak" "$pak_url" || die 'Unable to get the package'
        pak_fname="$temp_dir/package.pak"
esac

case $o_show in
    yes)
        output 'Contents:'
        tar -tf "$pak_fname"
        ;;
esac

case $o_install in
    yes)
        output "Installing $pak_fname"
        if ! ask "Do you really want to install package?"; then
            output 'Aborting'
            rm -rf "$temp_dir"
            exit 1;
        fi
        if tar -tf "$pak_fname" ./install.sh 2>/dev/null; then
            tar -xf "$pak_fname" ./install.sh
            output 'Running install.sh' -v
            bash install.sh "$pak_fname" || die 'Failed to install'
            rm install.sh
        else
            output "Unpacking to $root" -v
            tar -xf "$pak_fname" -C "$root" || die 'Failed to install'
        fi
        output "Successfully installed"
        rm -rf "$temp_dir"
        ;;
    uninstall)
        output "Uninstalling $pak_fname"
        if ! ask "Do you really want to uninstall package?"; then
            output 'Aborting'
            exit 1
        fi
        if tar -tf "$pak_fname" ./uninstall.sh 2>/dev/null; then
            tar -xf "$pak_fname" ./uninstall.sh
            output 'Running uninstall.sh' -v
            bash uninstall.sh "$pak_fname" || die 'Failed to uninstall'
            rm uninstall.sh
        else
            output "Going to remove:\n`tar -tf "$pak_fname" | sed "s#^#$root/#g"`"
            if ! ask 'Continue?'; then
                output 'Aborting'
                exit 1
            fi
            (tar -tf "$pak_fname" | sed "s#^#$root/#g" | xargs rm) || die 'Failed to uninstall'
        fi
        output 'Successfully uninstalled'
        ;;
    update)
        echo 'Updating package list'
        if ! [ -d "$paklist_dir" ]; then
            mkdir "$paklist_dir"
        fi
        case `ls "$paklist_dir" | wc -l` in
            0)
                echo "No lists to update"
                exit 1
                ;;
        esac
        for i in `ls "$paklist_dir"`; do
            f="$paklist_dir/$i"
            echo "Updating $f…"
            lnk="`head -n 1 $f`"
            if ! wget $lnk -O "$f.new"; then
                echo -e "\e[31mUnable to update $f\e[0m"
                continue
            fi
            mv "$f.new" "$f"
            echo -e "\e[32m$f updated successfully\e[0m"
        done
        echo "Done"
esac
