#!/usr/bin/env bash

set -e

# Configuration
pakroot="${pakroot:-"/"}"
temp_base_dir="${temp_base_dir:-"/tmp/pak"}"
temp_dir="$temp_base_dir/download-$RANDOM-$RANDOM-$RANDOM-$RANDOM/"
pakconfig="${pakconfig:-"/etc/pak"}"
pakvar="${pakvar:-"/var/pak"}"

mkdir -p "$temp_dir"
chmod a+rwt "$temp_base_dir" 2>/dev/null || true

help_exit_status=0

# String data
version="2.3 [beta] stupid"
version_string="PAK v $version"

usage_string="Usage: $0 [options] <action> [<package> [<package> ...]]"
help_string="
Action:
    install - install package from local file, <package> is filename
    get     - download package from mirror, don't install, <package> is package name
    mirror  - download and install package, <package> is package name
    update  - update mirror package index
    remove  - remove installed package, <package> is package name
    list    - list all available packages
    pakroot - print value of pakroot variable
    help    - Show this help screen and exit, do not parse options any further
Options:
    -h | --help     Same as 'help' action
    -V | --version  Show version information and exit
         --         Treat next options as filenames or package names
                    It is an error to use this option before specifying an action
Package:
    Not necessarily a package name like one in package index, it depends on actions.
    It is possible to provide a space-separated package list as one argument
    For example, this command is absolutely valid:
        pak mirror 'foo bar' baz
    and will install packages 'foo', 'bar' and 'baz'
"

# Options and actions, filled by command line arguments

o_help=none         # Show that kind of information and exit, 'none' means normal behavior
o_names=""          # Space-separated list of filenames or package names
o_ignore_depends=no # Ignore dependencies
o_action=help       # Action

# State variables
pkgpath=''

# Functions
function die() {
    rm -r "$temp_dir"
    echo -e "\e[31mFatal error: $1\e[0m" >&2
    exit 1
}
function ask() {
    echo -ne "$1"
    local ans
    read ans
    case $ans in
        y|yes|Y|Yes|YES)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

function show_help() {
    case $o_help in
        help)
            echo -e "$usage_string"    # TODO: legacy code, get rid of usage_string
            echo -e "$help_string"
            ;;
        version)
            echo -e "$version_string"
            ;;
        pakroot)
            echo "$pakroot"
            ;;
        # No request for printing help message
        *)
            return 0
            ;;
    esac
    return $help_exit_status
}

function is_installed() {
    if grep -xFq "$pakvar/pak_index.txt" -e "$1"; then
        return 0
    else
        return 1
    fi
}

function add_to_index() {
    if ! is_installed "$1"; then
        echo "$1" >> "$pakvar/pak_index.txt"
    fi
}

function remove_from_index() {
    if is_installed "$1"; then
        cat "$pakvar/pak_index.txt" | grep -xFv "$1" > "$pakvar/pak_index_tmp.txt"
        mv "$pakvar/pak_index_tmp.txt" "$pakvar/pak_index.txt"
    fi
}

function get_packages() {
    if [[ -z "$1" ]]; then
        help_exit_status=1 o_help=help show_help
        exit 1
    fi

    echo "Going to download packages: "
    local i
    for i in $1; do
        echo "    $i"
    done

    if ! ask "Continue? [y/n] "; then
        echo "Aborting."
        exit 1
    fi

    for i in $1; do
        if ! get_package "$i" --current-dir; then
            echo "Error: failed to download package '$i'"
            exit 1
        fi
    done
}

function list_packages() {
    local mirror_list="$pakconfig/mirrors/"
    local url=""
    local i
    for i in $(ls "$mirror_list"); do
        cat "$mirror_list/$i" | tail -n +2 | sed 's/: .*$//g' | while read pkgname; do
            if is_installed "$pkgname"; then
                echo -n "$pkgname"
                echo -ne " \e[32m[Installed]\e[0m" >&2
                echo
            else
                echo "$pkgname"
            fi
        done
    done
}

function get_package() {
    local mirror_list="$pakconfig/mirrors/"
    local url=""
    local i
    for i in $(ls "$mirror_list"); do
        local s="$(cat "$mirror_list/$i" | grep "^$1: ")"
        if [[ -n "$s" ]]; then
            local pak_url="$(echo "$s" | awk '{print $2}')"
            if [[ -z "$pak_url" ]]; then
                continue
            else
                break
            fi
        fi
    done
    if [[ -z "$pak_url" ]]; then
        echo "Package '$1' not found in the mirror list"
        return 1
    fi
    if [[ "$2" == "--current-dir" ]]; then
        declare -g pkgpath="./$1.pak"
    else
        declare -g pkgpath="$temp_dir/$RANDOM-$RANDOM-$RANDOM.pak"
    fi

    echo "Downloading $1..."

    if ! curl -L -o "$pkgpath" "$pak_url"; then
        echo "Failed to download $1"
        return 1
    fi
    return 0
}

function install_packages() {
    if [[ -z "$1" ]]; then
        help_exit_status=1 o_help=help show_help
        exit 1
    fi

    echo "Going to install packages: "
    local i
    for i in $1; do
        echo "    $i"
    done

    if ! ask "Continue? [y/n] "; then
        echo "Aborting."
        exit 1
    fi

    for i in $1; do
        if ! install_package_file "$i"; then
            echo "Failed to install $i"
            exit 1
        fi
    done
}

function remove_packages() {
    if [[ -z "$1" ]]; then
        help_exit_status=1 o_help=help show_help
        exit 1
    fi

    echo "Going to remove packages: "
    local i
    for i in $1; do
        echo "    $i"
    done

    if ! ask "Continue? [y/n] "; then
        echo "Aborting."
        exit 1
    fi

    local cnt=0
    for i in $1; do
        if ! remove_package "$i"; then
            echo "Failed to remove $i"
            exit 1
        fi
    done
}

function remove_package() {
    echo "Removing '$1'"
    if ! is_installed "$1"; then
        echo "Cannot remove package '$1': it is not installed"
        return 1
    fi
    if ! [[ -f "$pakvar/$1.files" ]]; then
        echo "Warning: cannot remove files of package '$i': file list is not present"
        echo "Warning appended to log: '$pakvar/pak.log'"
        echo "Warning: cannot remove files of package '$i': file list is not present" >> "$pakvar/pak.log"
    else
        local fil
        cat "$pakvar/$1.files" | while read fil; do
            rm -r "$pakroot/$fil"
        done
    fi
    remove_from_index "$1" || return 2
}

function install_package_file() {
    if ! [[ -e "$1" ]]; then
        echo "Installing package '$1' failed: file does not exist"
        return 1
    fi

    local temp_pkgname="$RANDOM-$RANDOM.tar.unknown"
    cp -- "$1" "$temp_dir/$temp_pkgname"
    mkdir "$temp_dir/$temp_pkgname.d"
    if ! tar -xf "$temp_dir/$temp_pkgname" -C "$temp_dir/$temp_pkgname.d/" .pak2/{deps,name}; then
        echo "Installation failed as package format is unknown"
        return 1
    fi
    local pkgname="$(cat $temp_dir/$temp_pkgname.d/.pak2/name)"

    echo "Installing ${pkgname}..."
    if is_installed "$pkgname"; then
        echo "Warning: package '$pkgname' is already installed, reinstalling..."
    fi

    local dep
    for dep in `cat $temp_dir/$temp_pkgname.d/.pak2/deps`; do
        if ! is_installed "$dep"; then
            if ! mirror_install_package_file "$dep"; then
                echo "Required dependency '$dep' not found"
                return 1
            fi
        fi
    done

    if tar -tf "$temp_dir/$temp_pkgname" .pak2/license >/dev/null 2>/dev/null; then
        tar -xf "$temp_dir/$temp_pkgname" -C "$temp_dir/$temp_pkgname.d/" .pak2/license
        local pager=cat
        if [[ "$(cat "$temp_dir/$temp_pkgname.d/.pak2/license" | wc -l)" -gt $(( "$(tput lines)" - 5 )) ]]; then
            pager=${PAGER:-less}
        fi

        {
            echo "You have to accept the following license to install the package."
            echo "This license will be installed at $pakvar/licenses/$pkgname/LICENSE."
            echo -e "\e[1m--- START LICENSE TEXT ---\e[0m"
            cat "$temp_dir/$temp_pkgname.d/.pak2/license"
            echo -e "\e[1m---  END LICENSE TEXT  ---\e[0m"
        } | "$pager"
        echo "Do you accept this license?"
        echo -n "[y/N]: "
        local ans
        read ans
        if [[ "$ans" == "y" ]]; then
            echo "License accepted"
        elif [[ "$ans" == "n" ]]; then
            echo "License not accepted, package will not be installed"
            return 1
        else
            echo "(assumed no)"
            echo "License not accepted, package will not be installed"
            return 1
        fi
        echo "Installing license..."
        mkdir -p "$pakvar/licenses/$pkgname/"
        cp "$temp_dir/$temp_pkgname.d/.pak2/license" "$pakvar/licenses/$pkgname/LICENSE"
    fi
    echo "Unpacking '$pkgname'..."
    local ret=0
    if [ -f "$pakvar/$pkgname.files" ]; then
        mv "$pakvar/$pkgname.files" "$pakvar/$pkgname.files.old"
    fi
    tar -xf "$temp_dir/$temp_pkgname" -C "$temp_dir/$temp_pkgname.d" || ret=1
    local i
    for i in `ls -A "$temp_dir/$temp_pkgname.d/files/"`; do
        cp --preserve --no-preserve=owner -r "$temp_dir/$temp_pkgname.d/files/$i" "$pakroot" || ret=1
    done
    for i in `find "$temp_dir/$temp_pkgname.d/files/" -type f`; do
        echo "$i" | sed "s#^$temp_dir/$temp_pkgname.d/files##g" >> "$pakvar/$pkgname.files"
    done
    if [[ $ret != 0 ]]; then
        echo "Failed to install package '${pkgname}'"
        if [ -f "$pakvar/$pkgname.files.old" ]; then
            mv "$pakvar/$pkgname.files.old" "$pakvar/$pkgname.files"
        fi
    else
        add_to_index "$pkgname"
        if [[ -f "$pakvar/$pkgname.files.old" ]]; then
            rm "$pakvar/$pkgname.files.old"
        fi
    fi
    return $ret
}

function update_package_lists() {
    echo 'Updating package lists'
    local mirror_list="$pakconfig/mirrors/"
    case $(ls "$mirror_list" | wc -l) in
        0)
            echo "No lists to update"
            return 1
            ;;
    esac
    local i
    for i in $(ls "$mirror_list"); do
        local f="$mirror_list/$i"
        case "$f" in
            *.new)
                continue
                ;;
        esac
        echo "Updating..."
        local lnk="$(head -n 1 $f)"
        if ! wget -q "$lnk" -O "$f.new"; then
            echo -e "Unable to update $f"
            continue
        fi
        cp "$f" "$pakconfig/backup/$i"
        mv "$f.new" "$f"
    done
    echo "Done"
}

function check_exist_package() {
    local mirror_list="$pakconfig/mirrors/"
    local url=""
    local i
    for i in $(ls "$mirror_list"); do
        local pkgname
        cat "$mirror_list/$i" | tail -n +2 | sed 's/: .*$//g' | while read pkgname; do
            if [[ "$pkgname" == "$1" ]]; then
                echo yes
                return 0
            fi
        done
    done
    echo no
}

function check_exist_packages() {
    local j
    for j in $1; do
        if [[ "$(check_exist_package "$j")" == "no" ]]; then
            echo "Unable to find package '$j' in mirror list"
            exit 1
        fi
    done
}

function mirror_install_packages() {
    if [[ -z "$1" ]]; then
        help_exit_status=1 o_help=help show_help
        exit 1
    fi

    check_exist_packages $1

    echo "Going to install packages: "
    local i
    for i in $1; do
        echo "    $i"
    done

    if ! ask "Continue? [y/n] "; then
        echo "Aborting."
        exit 1
    fi

    local cnt=0
    for i in $1; do
        if ! mirror_install_package_file "$i"; then
            echo "Failed to install package from file '$i'"
            exit 1
        fi
    done
}

function mirror_install_package_file() {
    get_package "$1" || return 1
    install_package_file "$pkgpath" || return 2
    return 0
}

# Temporary variables

t_all_names=no      # Interpret everything as a package or file name (if '--' option specified)
t_was_action=no     # Set to 'yes' when action specifier is read

# Parse args
while [[ -n "$1" ]]; do
    # If we treat all arguments as file/package names
    if [[ "$t_all_names" == "yes" ]]; then
        # Append file/package name to list
        o_names="$o_names $1"
        shift
        continue
    fi

    # Parse actions

    # install - install package from local file, <package> is filename
    # get     - download package from mirror, don't install, <package> is package name
    # mirror  - download and install package, <package> is package name
    # update  - update mirror package index
    # remove  - remove installed package, <package> is package name
    # pakroot - print value of pakroot variable
    # help    - Show this help screen and exit, do not parse options any further

    if [[ "$t_was_action" == "no" ]]; then
        t_is_action_valid="yes"
        case $1 in
            install)
                action=install
                ;;
            get)
                action=get
                ;;
            mirror)
                action=mirror
                ;;
            update)
                action=update
                ;;
            remove)
                action=remove
                ;;
            list)
                action=list
                ;;
            pakroot)
                o_help=pakroot
                action=help
                ;;
            help)
                o_help=help
                action=help
                ;;
            *)
                t_is_action_valid="no"
        esac

        if [[ "$t_is_action_valid" == "yes" ]]; then
            t_was_action="yes"
            shift
            continue
        fi
    fi


    # If we meet a '--help' or similar options (and we don't treat them as file/package names)
    case $1 in
        -h|--help)
            o_help=help
            show_help
            exit $?
            ;;
        -V|--version)
            o_help=version
            show_help
            exit $?
            ;;
        --)
            t_all_names="yes"
            shift
            continue
            ;;
    esac

    # Append file/package name to list
    o_names="$o_names $1"

    shift
done

if [[ "$t_was_action" == "no" ]]; then
    o_help=help
    show_help
    exit 1
fi

# o_names="`echo $o_names | xargs echo -- | sed 's/^-- \?//g'`"

if ! [[ -d "$pakroot" ]]; then
    echo "Directory '$pakroot' (PAK root) is missing, creating..."
    if ! mkdir -p "$pakroot"; then
        die "unable to create PAK root directory"
    fi
fi

case $action in
    install)
        if [[ "${EUID}" != 0 && "${PAK_NO_NONROOT_WARNING}" != '1' ]]; then
            echo "Warning: you run pak as a non-root user, this may cause 'Permission denied' errors"
            echo "If you don't want to see this message, set the environmental variable 'PAK_NO_NONROOT_WARNING' to 1"
        fi
        install_packages "$o_names"
        ;;
    get)
        get_packages "$o_names"
        ;;
    mirror)
        if [[ "${EUID}" != 0 && "${PAK_NO_NONROOT_WARNING}" != '1' ]]; then
            echo "Warning: you run pak as a non-root user, this may cause 'Permission denied' errors"
            echo "If you don't want to see this message, set the environmental variable 'PAK_NO_NONROOT_WARNING' to 1"
        fi
        mirror_install_packages "$o_names"
        ;;
    update)
        if [[ "${EUID}" != 0 && "${PAK_NO_NONROOT_WARNING}" != '1' ]]; then
            echo "Warning: you run pak as a non-root user, this may cause 'Permission denied' errors"
            echo "If you don't want to see this message, set the environmental variable 'PAK_NO_NONROOT_WARNING' to 1"
        fi
        update_package_lists
        ;;
    remove)
        if [[ "${EUID}" != 0 && "${PAK_NO_NONROOT_WARNING}" != '1' ]]; then
            echo "Warning: you run pak as a non-root user, this may cause 'Permission denied' errors"
            echo "If you don't want to see this message, set the environmental variable 'PAK_NO_NONROOT_WARNING' to 1"
        fi
        remove_packages "$o_names"
        ;;
    list)
        list_packages
        ;;
    help)
        case $o_help in
            help)
                show_help
                exit
                ;;
            pakroot)
                echo "$pakroot"
                exit
                ;;
        esac
        ;;
    *)
        die "invalid action: '$action'"
esac

rm -r "$temp_dir"
